local Luxt = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Luxware-UI-Library/main/Source.lua"))()

local MainWindow = Luxt.CreateWindow("Luxware Demo", 6105620301)

local homeTab = MainWindow:Tab("Home", 6034767608)
local widgetsTab = MainWindow:Tab("Widgets", 6031063897)
local settingsTab = MainWindow:Tab("Settings", 6055689952)
local creditsTab = MainWindow:Tab("Credits", 6015070412)

local homeSection = homeTab:Section("Welcome")
homeSection:Label("Welcome to Luxware UI Library!")
homeSection:Label("This is a comprehensive demo showcasing all available widgets.")
homeSection:Button("Click Me!", function()
    print("Button clicked!")
end)
homeSection:Toggle("Enable Feature", function(state)
    print("Toggle:", state)
end)

local sliderSection = homeTab:Section("Player Settings")
sliderSection:Slider("WalkSpeed", 16, 500, function(value)
    if game.Players.LocalPlayer.Character then
        game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = value
    end
end)
sliderSection:Slider("JumpPower", 50, 400, function(value)
    if game.Players.LocalPlayer.Character then
        game.Players.LocalPlayer.Character.Humanoid.JumpPower = value
    end
end)

local textboxSection = homeTab:Section("Input")
textboxSection:TextBox("Username", "Enter your name...", function(text)
    print("Username input:", text)
end)
textboxSection:TextBox("API Key", "Paste key here...", function(key)
    print("API Key saved")
end)

local widgetSection1 = widgetsTab:Section("Buttons")
widgetSection1:Label("Button Widget")
widgetSection1:Button("Primary Action", function()
    print("Primary action!")
end)
widgetSection1:Button("Secondary Action", function()
    print("Secondary action!")
end)

local widgetSection2 = widgetsTab:Section("Toggles")
widgetSection2:Label("Toggle Widget")
widgetSection2:Toggle("Auto-Farm", function(state)
    print("Auto-Farm:", state)
end)
widgetSection2:Toggle("Auto-Collect", function(state)
    print("Auto-Collect:", state)
end)
widgetSection2:Toggle("ESP", function(state)
    print("ESP:", state)
end)

local widgetSection3 = widgetsTab:Section("Sliders")
widgetSection3:Label("Slider Widget - Drag to adjust values")
widgetSection3:Slider("Volume", 0, 100, function(value)
    print("Volume:", value)
end)
widgetSection3:Slider("Sensitivity", 0.1, 10, function(value)
    print("Sensitivity:", value)
end)
widgetSection3:Slider("FOV", 60, 120, function(value)
    print("FOV:", value)
end)

local widgetSection4 = widgetsTab:Section("Dropdowns")
widgetSection4:Label("Dropdown Widget - Click to expand")
widgetSection4:DropDown("Select Game", {"Brookhaven", "Blox Fruits", "Arsenal", "Phantom Requiem", "Tower of Hell"}, function(selected)
    print("Selected game:", selected)
end)
widgetSection4:DropDown("Select Region", {"US-East", "US-West", "EU", "Asia", "Australia"}, function(selected)
    print("Selected region:", selected)
end)

local widgetSection5 = widgetsTab:Section("Keybinds")
widgetSection5:Label("Keybind Widget - Click to rebind")
widgetSection5:KeyBind("Toggle UI", Enum.KeyCode.LeftAlt, function()
    print("UI toggled!")
end)
widgetSection5:KeyBind("Execute Script", Enum.KeyCode.F, function()
    print("Script executed!")
end)
widgetSection5:KeyBind("Emergency Stop", Enum.KeyCode.G, function()
    print("Emergency stop!")
end)

local widgetSection6 = widgetsTab:Section("TextBoxes")
widgetSection6:Label("TextBox Widget - Type and press Enter")
widgetSection6:TextBox("Player Name", "Enter name...", function(text)
    print("Player name:", text)
end)
widgetSection6:TextBox("Teleport To", "Enter location...", function(text)
    print("Teleport to:", text)
end)
widgetSection6:TextBox("Custom Command", "Enter command...", function(text)
    print("Command:", text)
end)

local widgetSection7 = widgetsTab:Section("Labels")
widgetSection7:Label("This is a simple label")
widgetSection7:Label("Labels are great for descriptions")
widgetSection7:Label("They don't have interactivity")

local settingsSection1 = settingsTab:Section("UI Settings")
settingsSection1:Toggle("Dark Mode", function(state)
    print("Dark mode:", state)
end)
settingsSection1:Toggle("Show FPS", function(state)
    print("Show FPS:", state)
end)
settingsSection1:Toggle("Sound Effects", function(state)
    print("Sound effects:", state)
end)

local settingsSection2 = settingsTab:Section("Performance")
settingsSection2:Slider("Max FPS", 30, 240, function(value)
    print("Max FPS:", value)
end)
settingsSection2:DropDown("Quality", {"Low", "Medium", "High", "Ultra"}, function(selected)
    print("Quality:", selected)
end)

local settingsSection3 = settingsTab:Section("Keybinds")
settingsSection3:KeyBind("Toggle GUI", Enum.KeyCode.V, function()
    print("GUI toggled!")
end)
settingsSection3:KeyBind("Reset Settings", Enum.KeyCode.R, function()
    print("Settings reset!")
end)

local creditsSection1 = creditsTab:Section("Main Credits")
creditsSection1:Credit("xHeptc - Main Developer")
creditsSection1:Credit("Luxware UI Library")

local creditsSection2 = creditsTab:Section("UI Credits")
creditsSection2:Credit("Design by xHeptc")
creditsSection2:Credit("Wave decoration asset from Roblox")

local creditsSection3 = creditsTab:Section("Special Thanks")
creditsSection3:Credit("v3rmillion community")
creditsSection3:Credit("Eazvy for maintaining the UILibs repo")